### PR TITLE
initial commit of Matlab version

### PR DESCRIPTION
**Pull request by RenoFilla**
initial commit of Matlab version

Signed-off-by: Reno Filla <reno.filla@gmx.net>

### CODE REVIEW

**Comment by lene** [comment]
Thanks for this! Since you labeled it as "initial commit", I am not sure if you consider it ready for review yet. Either way, would you mind adding some tests to ensure code correctness, please?

**Comment by RenoFilla** [comment]
> Thanks for this! Since you labeled it as "initial commit", I am not sure if you consider it ready for review yet. Either way, would you mind adding some tests to ensure code correctness, please?

I only commit working code. ;-) It's been used heavily at my day job. I don't know how to add automated tests. It works as intended, take any example you want.

**Comment by RenoFilla** [comment]
> Either way, would you mind adding some tests to ensure code correctness, please?

Test added.

**Comment by RenoFilla** [comment]
If there is anything preventing this from being accepted please notify me. The code is final, it is proven to work, tests are added, everything signed as required.

If I might add: the amount of hours I had to spent to attend to issues to get the code approved (even though it still isn't) outnumbers the amount of hours spent on actual code development by factor 2.

**Review by lene — APPROVED** [review]

**Pull request merged**
